apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: examples-stage

commonLabels:
  environment: stage

resources:
- ../../base

images:
- digest: sha256:016a812d01c512faf5f37564531a95efe9a7ecc444801cfa74cf2e33aecfa4c7
  name: quay.io/gh-stocky37/greeting-ui

configMapGenerator:
- name: greeting-ui-config
  files:
  - env.js

# prefix route url with environment subdomain
replacements:
- source:
    kind: Route
    fieldPath: metadata.labels.environment
  targets:
  - select:
      kind: Route
    fieldPaths: ['spec.host']
    options:
      delimiter: '.'
      index: -1
