apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev

components:
  - ../../../components/argocd-hooks

configMapGenerator:
  - name: postsync-env
    behavior: merge
    literals:
      - ENVIRONMENT=dev
