apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: prod

resources:
- app
- argocd

images:
- digest: sha256:f14367878efb0c8ac0895622e8cc42ac8cfec648af18615eb8eb3fed62c5824d
  name: quay.io/tstockwell/greeting-ui
