apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev

resources:
  - ../../../../components/argocd-hook

configMapGenerator:
  - name: hook-config
    behavior: merge
    literals:
      - ENVIRONMENT=dev
      - WEBHOOK_URL=http://webhooks.demo-gitops-cicd-cicd.apps.paas.lab.stocky37.dev
