apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-gitops-cicd-gitops
namePrefix: greeting-ui-

commonLabels:
  app: greeting-ui

resources:
  - https://github.com/tom-stockwell/gitops-common//argocd-hook/variants/postsync?ref=main

configMapGenerator:
  - name: hook-config
    behavior: merge
    literals:
      - APP_NAME=greeting-ui
