apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  app.openshift.io/vcs-uri: https://github.com/tom-stockwell/greeting-ui.git
  app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"greeting-api"}]'

commonLabels:
  app: &app greeting-ui
  app.kubernetes.io/name: *app
  app.kubernetes.io/instance: *app
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: greeting-app
  app.openshift.io/runtime: react

resources:
- deployment.yml
- route.yml
- service.yml
