apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: greeting-ui
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: greeting-ui
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
