apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: examples-dev

commonLabels:
  environment: dev

resources:
- ../../base

images:
- digest: sha256:016a812d01c512faf5f37564531a95efe9a7ecc444801cfa74cf2e33aecfa4c7
  name: quay.io/gh-stocky37/greeting-ui

configMapGenerator:
- files:
  - env.js
  name: greeting-ui-config

# prefix route url with environment subdomain
replacements:
- source:
    fieldPath: metadata.labels.environment
    kind: Route
  targets:
  - fieldPaths:
    - spec.host
    options:
      delimiter: .
      index: -1
    select:
      kind: Route
